name: Frontend Build-Action
description: 'build and push to s3'

inputs:
  PAT:
    description: 'PAT from repo'
    required: true
  NODE_VERSION:
    description: 'node version'
    required: false
    default: 'latest'
  WORKING_DIRECTORY:
    description: 'working directory'
    required: true
    default: ''
  MONOREPO_MODE:
    description: 'monorepo mode'
    required: false
    default: 'false'
  BUCKET_NAME:
    description: 'bucket name'
    required: true
  OUTPUT_PATH:
    description: 'output path'
    required: false
    default: 'dist'

outputs:
  bucket_name: 
    description: 'bucket_name'
    value: ${{ steps.bucket_name.outputs.bucket_name }}

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v6

  - name: Use Node.js ${{ inputs.NODE_VERSION }}
    uses: actions/setup-node@v6
    with:
      node-version: ${{ inputs.NODE_VERSION }}
      cache: 'npm'

  - name: Authenticate with private NPM package
    run: |
      echo "@entrecode:registry=https://npm.pkg.github.com/" > ./.npmrc
      echo "//npm.pkg.github.com/:_authToken=${{ inputs.PAT }}" > ./.npmrc
    working-directory: ${{ inputs.MONOREPO_MODE == 'true' && github.workspace || format('{0}/{1}', github.workspace, inputs.WORKING_DIRECTORY) }}
    shell: bash

  - name: Check file existence pnpm
    id: check_files_pnpm
    uses: andstor/file-existence-action@v3
    with:
      files: 'pnpm-lock.*'

  - name: Setup pnpm
    if: steps.check_files_pnpm.outputs.files_exists == 'true'
    uses: pnpm/action-setup@v4
    with:
      version: 9

  - name: Install pnpm
    if: steps.check_files_pnpm.outputs.files_exists == 'true'
    run: pnpm install --frozen-lockfile --prefer-offline --reporter=silent
    shell: bash

  - name: Install Dependencies
    if: steps.check_files_pnpm.outputs.files_exists != 'true'
    run: npm ci --prefer-offline --no-audit --quiet
    working-directory: ${{ inputs.MONOREPO_MODE == 'true' && github.workspace || format('{0}/{1}', github.workspace, inputs.WORKING_DIRECTORY) }}
    shell: bash

  - name: Build stage with pnpm
    if: steps.check_files_pnpm.outputs.files_exists == 'true' && startsWith(github.ref, 'refs/tags/') != true && startsWith(github.ref, 'refs/heads/release/') != true
    id: build_stage_pnpm
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    run: |
      pnpm run stage
      echo "bucket_name=${{ inputs.BUCKET_NAME }}-stage" >> $GITHUB_OUTPUT
    working-directory: ${{ github.workspace }}/${{ inputs.WORKING_DIRECTORY }}
    shell: bash

  - name: Build stage with npm
    if: steps.check_files_pnpm.outputs.files_exists != 'true' && startsWith(github.ref, 'refs/tags/') != true && startsWith(github.ref, 'refs/heads/release/') != true
    id: build_stage
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    run: |
      npm run stage
      echo "bucket_name=${{ inputs.BUCKET_NAME }}-stage" >> $GITHUB_OUTPUT

    working-directory: ${{ github.workspace }}/${{ inputs.WORKING_DIRECTORY }}
    shell: bash

  - name: Build staging with pnpm
    if: steps.check_files_pnpm.outputs.files_exists == 'true' && startsWith(github.ref, 'refs/heads/release/')
    id: build_staging_pnpm
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    run: |
      pnpm run staging
      echo "bucket_name=${{ inputs.BUCKET_NAME }}-staging" >> $GITHUB_OUTPUT
    working-directory: ${{ github.workspace }}/${{ inputs.WORKING_DIRECTORY }}
    shell: bash

  - name: Build staging with npm
    if: steps.check_files_pnpm.outputs.files_exists != 'true' && startsWith(github.ref, 'refs/heads/release/')
    id: build_staging
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    run: |
      npm run staging
      echo "bucket_name=${{ inputs.BUCKET_NAME }}-staging" >> $GITHUB_OUTPUT

    working-directory: ${{ github.workspace }}/${{ inputs.WORKING_DIRECTORY }}
    shell: bash

  - name: Build prod with pnpm
    if: steps.check_files_pnpm.outputs.files_exists == 'true' && startsWith(github.ref, 'refs/tags/')
    id: build_prod_pnpm
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    run: |
      pnpm run prod
      echo "bucket_name=${{ inputs.BUCKET_NAME }}-prod" >> $GITHUB_OUTPUT
    working-directory: ${{ github.workspace }}/${{ inputs.WORKING_DIRECTORY }}
    shell: bash
    
  - name: Build prod with npm
    if: steps.check_files_pnpm.outputs.files_exists != 'true' && startsWith(github.ref, 'refs/tags/')
    id: build_prod
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    run: |
      npm run prod
      echo "bucket_name=${{ inputs.BUCKET_NAME }}-prod" >> $GITHUB_OUTPUT

    working-directory: ${{ github.workspace }}/${{ inputs.WORKING_DIRECTORY }}
    shell: bash

  - name: Create Bucket Name Output
    id: bucket_name
    run: echo "bucket_name=${{ steps.build_stage.outputs.bucket_name || steps.build_staging.outputs.bucket_name || steps.build_prod.outputs.bucket_name }}" >> $GITHUB_OUTPUT
    shell: bash

  - name: Upload build artifact
    uses: actions/upload-artifact@v5
    with:
      name: build_result
      path: ${{ github.workspace }}/${{ inputs.WORKING_DIRECTORY }}/${{ inputs.OUTPUT_PATH }}/
      retention-days: 2
